- lib/ChakraRunner.js
- lib/ConsoleRunner.js
- lib/D8Runner.js
- lib/JSCRunner.js
- lib/NashornRunner.js
- lib/NodeRunner.js
- lib/SMRunner.js
- lib/runify.js
- runtimes/d8.js
- runtimes/jsc-create.js
- runtimes/jsc.js
- runtimes/nashorn.js
- runtimes/sm.js
- test/runify.js
A small :gift: for you! :smile: 
I had to disable the 'can eval lexical bindings in new scripts' test for JSC, because I haven't found a way to run arbitrary code as global script code in JSC. 
Tested all changes with JSC, Node, SM, V8 (recent builds from tip/master); Nashorn (JDK8 and JDK9b96).
(The first commit is only clean-up, so you can skip that one if you feel it's not necessary to include it.)
> JSC and Nashorn runners

- README.md
- runtimes/browser.js
- runtimes/chakra.js
- runtimes/d8.js
- runtimes/jsc.js
- runtimes/nashorn.js
- runtimes/node.js
- runtimes/sm.js
- test/runify.js
Directly accessing properties from other realms throws `TypeError: no access` in d8.
> Add $.getGlobal to access properties from other globals

- lib/ConsoleRunner.js
- lib/JSCRunner.js
- runtimes/jsc.js
- test/runify.js
Another workaround for missing JSC shell built-ins: The built-in `load()` function executes source code as a script, so just what we need for our `evalInNewScript` function (yay!). But `load()` only accepts a file parameter and JSC doesn't provide a built-in function to write to files (meh!). As a workaround I'm simply delegating the file write access to the node process.
> Add proper script-load support for JSC

- lib/parseError.js
I ran into a failure here when running the test suite. I assume returning null on a bad error props match is OK because this code was already returning null on line 13. But perhaps that is a bad assumption?
> Don't crash when unable to parse error props

- README.md
- lib/Agent.js
- test/runify.js
This is a rebased version of the changeset initially submitted by @littledan in gh-19. As noted in that discussion, recent changes in `master` necessitated a rebase and subsequent modification (see the final commit on this branch).
Supersedes gh-19.
> Allow a transpiler to be provided for an agent (rebased)

- lib/WebdriverAgent.js
When a Socket.io server with active connections is destroyed, it may
fail to clear long-running internal timers. The process will not exit
while such timers are active, causing significant delays between server
destruction and process termination.
Re-order the sequence of actions in the WebDriverAgent's `destroy`
method to first end the browsing session (allowing all Socket.io-related
timers to be cleared) and then destroy the Socket.io server.
> Avoid timeout bug in Socket.io

- test/runify.js
Organize tests into dedicated Mocha.js "suites" according to their
initialization requirements. This reduces the amount of duplication in
test setup (specifically related to test skipping and timeout values),
and it produces more descriptive logging output.
> Refactor test code

- lib/ConsoleAgent.js
- lib/WebdriverAgent.js
- lib/agents/BrowserAgent.js
- test/runify.js
The host may need to perform a number of asynchronous operations in
order to evaluate a script. If the `stop` method is invoked while these
operations are taking place, the host should not evaluate the script.
---
Hey @bterlson! I stumbled across this bug while working on that new version of
the `test262-harness` Node.js API we talked about a couple weeks ago.
> Avoid race condition in `ConsoleAgent#stop`

- runtimes/browser.js
- runtimes/chakra.js
- runtimes/d8.js
- runtimes/jsc.js
- runtimes/nashorn.js
- runtimes/node.js
- runtimes/sm.js
- test/runify.js
To support this issue created in [Test262](https://github.com/tc39/test262/pull/1287), @jswalden proposed the addition of this host api extension.
> Add uncallableAndIsHTMLDDA support

- lib/agents/jsc.js
- runtimes/d8.js
- runtimes/jsc-create.js
- runtimes/jsc.js
- runtimes/sm.js
- test/runify.js
JSC:
- Switch to the new `createGlobalObject()` and `loadString()` functions. A whole lot of additional code is now no longer needed.
- Update the host arguments test now that WebAssembly is enabled by default.
V8:
- Use `Realm.createAllowCrossRealmAccess()` to allow direct access to global properties from other realms.
- Renamed the variables in `$.createRealm()` to make the code more similar to the other runtimes.
- Always set `$.realm` to the current realm-id to avoid possible differences in `$.evalScript` when called from the initial realm (realm-id = 0) compared to when `$.evalScript` is called from child-realms (realm-id > 0). (In the initial global, `$.realm` wasn't set, so the check in `this.realm ? ...` always evalutes to false, which means when a child-realm calls …
> Update runtime scripts for JSC, V8, and SpiderMonkey

- lib/ConsoleAgent.js
- lib/agents/jsc.js
- package.json
- runtimes/jsc.js
See: https://github.com/WebKit/webkit/blob/aeed7ff2493053fb9ffcc06fedc7e75311bacc8a/Source/JavaScriptCore/jsc.cpp#L574-L604
This enables tests that require $262.agent.*
I'm using `var jsc = this["\x24"];` instead of just writing `var jsc = $;`, or even just extending `$` if it exists, because the contents of the files in `runtimes/*` are not executed exactly as they appear. Each file experiences some amount of "processing" that will change the actual text content that eventually gets prepended to the test262 test source code. The bare minimum change that's applied is replacing all occurrences of `$` to `$262` (or whatever the `shortName` property is set to). Unfortunately, that means we cannot rely on the existence of an Identifier `$` (or `$262`) in that code.
> runtime/jsc: update to use JavaScriptCore's built-in $/$262

- lib/agents/jsc.js
> #52 DYLD_FRAMEWORK_PATH string match for JSC Agent: removing top level webkit directory string match to avoid casing or rename mismatches

- lib/ConsoleAgent.js
- test/fixtures/fake-test262/test/language/module-code/instn-iee-bndng-cls.js
- test/fixtures/fake-test262/test/language/module-code/instn-iee-bndng-cls_FIXTURE.js
- test/fixtures/fake-test262/test/language/module-code/instn-iee-bndng-const.js
- test/fixtures/fake-test262/test/language/module-code/instn-iee-bndng-const_FIXTURE.js
- test/fixtures/fake-test262/test/language/module-code/instn-iee-bndng-fun.js
- test/fixtures/fake-test262/test/language/module-code/instn-iee-bndng-fun_FIXTURE.js
- test/fixtures/fake-test262/test/language/module-code/instn-iee-bndng-gen.js
- test/fixtures/fake-test262/test/language/module-code/instn-iee-bndng-gen_FIXTURE.js
- test/fixtures/fake-test262/test/language/module-code/instn-iee-bndng-let.js
- test/fixtures/fake-test262/test/language/module-code/instn-iee-bndng-let_FIXTURE.js
- test/fixtures/fake-test262/test/language/module-code/instn-iee-bndng-var.js
- test/fixtures/fake-test262/test/language/module-code/instn-iee-bndng-var_FIXTURE.js
This code only existed to allow 6 Test262 tests to run. INTERPRETING.md now disallows the use of "Test262-Defined Bindings" and "Host-Defined Functions" inside _FIXTURE.js files.
> Remove dependency preamble building operations

- lib/ConsoleAgent.js
Hi,
Currently, eshost (and eshost-cli) doesn't log unexpected signals (e.g., SIGSEGV) from the child process. As some of the supported JS engines are still in development, this can suppress errors when the engine seg-faults. At this time, seg-faulting test-cases have no output on affected engines and appear to exit successfully.
I noticed SIGKILL was used internally for process control, so my patch captures all signals other than SIGKILL.
This PR should also provide better support for eshost-cli e.g., https://github.com/bterlson/eshost-cli/issues/55 
Thank you!
> ConsoleAgent: Log unexpected signals to stderr

- lib/agents/node.js
- runtimes/node.js
To allow the runtime to be used with very old versions of node that predate es6 support (like `node 0.10`). It used to be like this before https://github.com/bterlson/eshost/pull/41 and https://github.com/bterlson/eshost/pull/28 which were by and large unrelated to _explicitly_ dropping support for older hosts in the test runtime, seems like; so it'd be nice to still support them, IMO.
> Use only pre-es6 syntax in the `node` runtime

- runtimes/jsc.js
Real `$262.IsHTMLDDA` was implemented in [r259587](https://trac.webkit.org/changeset/259587).
> Remove IsHTMLDDA stub for JSC

- lib/agents/jsshell.js
- runtimes/jsshell.js
11bf59d:
- Adds the upstream changes from https://bugzilla.mozilla.org/show_bug.cgi?id=1473000
9b99cc6:
- Allows that the error message is absent in "uncaught exceptions".
- This ensures `throw new Test262Error()` in test262 is correctly handled.
- For example all tests in <https://test262.report/browse/annexB/language/comments> are currently marked as failing in SpiderMonkey, even though SpiderMonkey actually passes these tests. It's just that `eshost` doesn't correctly parse the error string reported from SpiderMonkey.
505e5c4:
- Improves the error parser to include stack frames.
> Spidermonkey updates

- lib/dependencies.js
- test/fixtures/fake-test262/test/language/module-code/import-assertion-1_FIXTURE.js
- test/fixtures/fake-test262/test/language/module-code/import-assertion-2_FIXTURE.js
- test/fixtures/fake-test262/test/language/module-code/import-assertion-dynamic.js
- test/fixtures/fake-test262/test/language/module-code/import-assertion-static.js
Update the patterns used to detect module dependencies to tolerate
string literals which may appear on the same line as module specifiers.
Further improve the pattern so that it does not match all
U+0022-delimited string literals and so that it does not require a
trailing semicolon.
> Improve robustness of dependency inference

- runtimes/jsc.js
- test/runify.js
A recent commit [1] regressed support for JavaScriptCore by changing the
way the "runtime" object is defined for that engine. Restore the
intended behavior and add an automated test.
[1] 4e9c3ee9b2c8cb1578e5bd9af18a028890b35b4d
---
The CI system is not currently configured to validate this change (or any other change) in JavaScriptCore. See gh-112 for that.
The regression has been observed in results published to test262.report: https://github.com/bocoup/test262-report-issue-tracker/issues/28
> Correct definition of JSC "runtime" object

- README.md
- lib/agents/libjs.js
- lib/supported-hosts.js
- runtimes/libjs.js
- test/runify.js
- test/supported-hosts.js
This adds very basic support for LibJS, SerenityOS's javascript engine (which can also be compiled for linux/mac/etc via Lagom).
the $262 support is mostly stubbed out, as that native object is added externally by https://github.com/linusg/libjs-test262 for LibJS, so until we move that into the main repository behind a feature flag it's inaccessible to the normal cli.
several tests were also skipped for libjs, but we should be able to gradully re-enable them as they are fixed in LibJS.
~This depends on https://github.com/SerenityOS/serenity/pull/11049.~ Merged
> Add SerenityOS's LibJS
